import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Header from "../components/header";
import MenuSection from "../components/menu_section";
import Navigation from "../components/navigation";
import SpaceSection from "../components/space_section";
import WelcomeSection from "../components/welcome_section";

export default function Home() {
  const [openNavigation, setOpenNavigation] = useState(false);
  const [isOpen, setOpen] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full">
        <Header
          setOpenNavigation={setOpenNavigation}
          isIconOpen={isOpen}
          setIconOpen={setOpen}
        />
        <Navigation
          openNavigation={openNavigation}
          setOpenNavigation={setOpenNavigation}
          setIconOpen={setOpen}
        />
        <WelcomeSection />
        <SpaceSection />
        <div
          className="bg-center bg-no-repeat h-screen mt-[50px]"
          style={{
            backgroundImage: `url(https://www.restaurantfrantzen.com/wp/wp-content/uploads/2021/11/Frantzen_Book_4100-scaled.jpg)`,
            backgroundSize: "auto 100%",
          }}
        ></div>
        <MenuSection />
      </main>

      <footer></footer>
    </div>
  );
}
